/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// model attribution: plasmaernst https://sketchfab.com/3d-models/fountain-e6370546c6204bf3bdde275113956585

import * as THREE from 'three'
import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

const FAUCET_URL = `${process.env.REACT_APP_CDN_BASE_URL}/fountain.gltf`;

type GLTFResult = GLTF & {
  nodes: {
    Object_24: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['m_fountain.001']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'FountainBones|ArmatureAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(FAUCET_URL) as GLTFResult
  // @ts-ignore
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useEffect(() => {
    // @ts-ignore
    if(actions['FountainBones|ArmatureAction']) {
      // @ts-ignore
      actions['FountainBones|ArmatureAction'].play();
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group name="215894519faf49b8ae450b3291cf1dc1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Fountain_Mesh" position={[0, 0, -587.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="FountainBones" rotation={[0, 0, -Math.PI / 2]}>
                    <group name="Object_6">
                      <group name="Object_23" position={[0, 0, -587.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['m_fountain.001']} skeleton={nodes.Object_24.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FAUCET_URL)

